I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 296, in script
    Prot "Anda hanya mengangguk"
Exception: Sayer 'Prot' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 296, in script
    Prot "Anda hanya mengangguk"
  File "C:\Users\LENOVO\Downloads\renpy-8.3.3-sdk\renpy\ast.py", line 2573, in execute
    Say.execute(self)
  File "C:\Users\LENOVO\Downloads\renpy-8.3.3-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\LENOVO\Downloads\renpy-8.3.3-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'Prot' is not defined.

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.3.24111502
TUBES 1.0
Tue Dec 10 06:36:07 2024
